### ISSUE TITLE
🐞 [Bug]: Conflict ESM <> CJS for custom step definitions.

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#302]
### What happened?

Currently the RestQA is written is CJS, but when RestQA has to test a project in ESM while RestQA is trying to load the custom step definition file: `tests/steps.js` an error will occurred...

### Relevant log output

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/olivierodo/WORKS/restqa/restqa/packages/screenshot/tests/steps.js from /Users/olivierodo/WORKS/restqa/restqa/packages/cli/dist/src/setup.js not supported.
steps.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename steps.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/olivierodo/WORKS/restqa/restqa/packages/screenshot/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at sR.exports (/Users/olivierodo/WORKS/restqa/restqa/packages/cli/dist/src/setup.js:193:23164)
    at Object.<anonymous> (/Users/olivierodo/WORKS/restqa/restqa/packages/cli/dist/src/setup.js:193:24342)
    at /Users/olivierodo/WORKS/restqa/restqa/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/lib/cli/index.js:122:17
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (/Users/olivierodo/WORKS/restqa/restqa/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/lib/cli/index.js:120:26)
    at Cli.run (/Users/olivierodo/WORKS/restqa/restqa/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/lib/cli/index.js:145:41)
    at async IC.parseAsync (/Users/olivierodo/WORKS/restqa/restqa/packages/cli/dist/bin/restqa:168:3909)
codepath: /Users/olivierodo/WORKS/restqa/restqa/packages/cli/dist/src/setup.js
```

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
In order to fix the issue we should look at using a `.cjs` file instead of `.js` file.
Then the conflict should be solved...
Steps:
1. During the initialization change the extension of the file that will be generated:  https://github.com/restqa/restqa/blob/master/packages/cli/src/core/initialize.js#L154
2. During the run of restqa, load the `tests/index.cjs` along with `tests/index.js`: https://github.com/restqa/restqa/blob/master/packages/cli/src/core/bootstrap.js#L88
3. Update the tests 😅
4. Look at impact on other packages (example: https://github.com/restqa/restqa/blob/master/packages/sandbox/tests/steps.js)
5. And voila!
