### ISSUE TITLE
🐞 [Bug]:  Plugin-mongoDB mock installation fail

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#309]
### What happened?

Currently there is a major bug on the Installation of the plugin `plugin-mongodb-mock`, the main entrypoint is pointing on a file that does not exist:
https://github.com/restqa/restqa/blob/7acc8adf9349e321c9e7da17addfa992602a8f75/packages/plugin-mongodb-mock/package.json#L5

It should point at: https://github.com/restqa/restqa/blob/master/packages/plugin-mongodb-mock/src/index.js

### Relevant log output

```shell
> dashboard@1.0.0 test
> restqa run

🎯 The selected environment is: "local"
Error: Cannot find module '/Users/olivierodo/WORKS/restqa/website/dashboard/node_modules/@restqa/plugin-mongodb-mock/index.cjs'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:400:19)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/olivierodo/WORKS/restqa/website/dashboard/node_modules/@restqa/restqa/dist/src/setup.js:193:23367
    at Array.map (<anonymous>)
    at sR.exports (/Users/olivierodo/WORKS/restqa/website/dashboard/node_modules/@restqa/restqa/dist/src/setup.js:193:22882)
    at Object.<anonymous> (/Users/olivierodo/WORKS/restqa/website/dashboard/node_modules/@restqa/restqa/dist/src/setup.js:193:24257)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
codepath: /Users/olivierodo/WORKS/restqa/website/dashboard/node_modules/@restqa/restqa/dist/src/setup.js
> 🏹 Target url: http://localhost:8082
❌ FAILED - Welcome to the RestQA community > Initial scenario
    TypeError: this.getConfig is not a function
    at World.createApi (/Users/olivierodo/WORKS/restqa/website/dashboard/node_modules/@restqa/plugin-rest-api/dist/index.js:33:1596)
    at ../../../../tests/local/get.feature:4
---
1 failed, 1 total
---
```

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
Actually another issue that need to be solve, is to convert all the  file into`.cjs` then also manage the potential conflict between CJS and ESM.
